package com.example.toor.yamblzweather.data.database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "WEATHER_MODEL".
 */
@Entity
public class WeatherModel {

    @Id(autoincrement = true)
    private Long id;
    private int cityId;
    private String currentWeather;
    private String forecastWeather;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public WeatherModel() {
    }

    public WeatherModel(Long id) {
        this.id = id;
    }

    @Generated
    public WeatherModel(Long id, int cityId, String currentWeather, String forecastWeather) {
        this.id = id;
        this.cityId = cityId;
        this.currentWeather = currentWeather;
        this.forecastWeather = forecastWeather;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getCityId() {
        return cityId;
    }

    public void setCityId(int cityId) {
        this.cityId = cityId;
    }

    public String getCurrentWeather() {
        return currentWeather;
    }

    public void setCurrentWeather(String currentWeather) {
        this.currentWeather = currentWeather;
    }

    public String getForecastWeather() {
        return forecastWeather;
    }

    public void setForecastWeather(String forecastWeather) {
        this.forecastWeather = forecastWeather;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
