package com.example.toor.yamblzweather.data.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "WEATHER".
 */
@Entity
public class Weather {

    @Id(autoincrement = true)
    private Long id;
    private double latitude;
    private double longitude;
    private String currentWeather;
    private String forecastWeather;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Weather() {
    }

    public Weather(Long id) {
        this.id = id;
    }

    @Generated
    public Weather(Long id, double latitude, double longitude, String currentWeather, String forecastWeather) {
        this.id = id;
        this.latitude = latitude;
        this.longitude = longitude;
        this.currentWeather = currentWeather;
        this.forecastWeather = forecastWeather;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public String getCurrentWeather() {
        return currentWeather;
    }

    public void setCurrentWeather(String currentWeather) {
        this.currentWeather = currentWeather;
    }

    public String getForecastWeather() {
        return forecastWeather;
    }

    public void setForecastWeather(String forecastWeather) {
        this.forecastWeather = forecastWeather;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
